plugins {
    id 'dev.architectury.loom' version '1.11-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.gradleup.shadow' version '8.3.+' apply false
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    version = rootProject.mod_version
    group = rootProject.maven_group
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        archivesName = "$rootProject.mod_id-$project.name"
    }

    loom {
        runs {
            client {
                property 'mixin.debug.export', 'true'
            }
        }
    }

    repositories {
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.terraformersmc.com" }

        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.layered {
            it.mappings("net.fabricmc:yarn:$rootProject.yarn_mappings:v2")
            it.mappings("dev.architectury:yarn-mappings-patch-neoforge:$rootProject.yarn_mappings_patch_neoforge_version")
        }
    }

    java {
        withSourcesJar()
        sourceCompatibility = targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    jar {
        from("LICENSE") {
            rename { "${it}_${rootProject.mod_id}" }
        }
    }

    processResources {
        def props = [
                version: project.version, minecraft_version: project.minecraft_version,
                description: project.mod_description, display_name: project.display_name, mod_id: project.mod_id
        ]
        inputs.properties props
        filteringCharset "UTF-8"

        filesMatching(["fabric.mod.json", "META-INF/neoforge.mods.toml"]) {
            expand props
        }
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
            }
        }

        // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
        repositories {
        }
    }
}