# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=2.2.1+26.1
maven_group=de.dafuqs
archives_base_name=HeadInTheClouds

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.19.2
loom_version=1.15-SNAPSHOT