# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
fabric_loader_version=0.18.3
neoforge_version=21.11.13-beta

# Mod Properties
mod_version=2.1.0+1.21.11
maven_group=de.dafuqs
mod_id=head_in_the_clouds
display_name=Head in the Clouds
mod_description=Make it not rain over the cloud level
enabled_platforms=fabric,neoforge