# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
fabric_loader_version=0.17.2
neoforge_version=21.8.47
yarn_mappings_patch_neoforge_version=1.21+build.4

# Mod Properties
mod_version=2.1.0+1.21.8
maven_group=de.dafuqs.head_in_the_clouds
mod_id=head_in_the_clouds
display_name=Head in the Clouds
mod_description=Make it not rain over the cloud level
enabled_platforms=fabric,neoforge